name: gdg_uganda
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0
  jaspr: ^0.16.1
  jaspr_router: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.16.1
  jaspr_lints: ^0.1.2
  jaspr_web_compilers: ^4.0.10+1
  lints: ^3.0.0

jaspr:
  mode: static
